name: setap4a
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.0
  sqflite: 2.4.1
  sqflite_common_ffi: ^2.0.0
  path: ^1.8.3
  firebase_auth: ^5.4.2
  firebase_core: ^3.11.0
  cloud_firestore: ^5.6.0
  test: ^1.25.8
  image_picker: ^1.0.7
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.17
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
     - assets/paris.jpg
     - assets/tokyo.jpg
     - assets/nyc.jpg
