// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyBTtS8dRCfr_E6QbsODpxCoPv7zS4nbFKs",
      authDomain: "setap-4a.firebaseapp.com",
      projectId: "setap-4a",
      storageBucket: "setap-4a.firebasestorage.app",
      messagingSenderId: "342998131788",
      appId: "1:342998131788:web:b308a5d521b6088f3cc0e9",
      measurementId: "G-L0PKQHJQT6");

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-okU08cFdoLXoiaoYLhfyISPLDQ-1sx0',
    appId: '1:342998131788:android:57665efcb08b51063cc0e9',
    messagingSenderId: '342998131788',
    projectId: 'setap-4a',
    storageBucket: 'setap-4a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQSX9A6kOgpYGZJ66MJ0Unj1-3g1oo58U',
    appId: '1:342998131788:ios:cd09db85225d671a3cc0e9',
    messagingSenderId: '342998131788',
    projectId: 'setap-4a',
    storageBucket: 'setap-4a.firebasestorage.app',
    iosBundleId: 'com.example.seCw',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQSX9A6kOgpYGZJ66MJ0Unj1-3g1oo58U',
    appId: '1:342998131788:ios:cd09db85225d671a3cc0e9',
    messagingSenderId: '342998131788',
    projectId: 'setap-4a',
    storageBucket: 'setap-4a.firebasestorage.app',
    iosBundleId: 'com.example.seCw',
  );

  static const FirebaseOptions windows = FirebaseOptions(
      apiKey: "AIzaSyBTtS8dRCfr_E6QbsODpxCoPv7zS4nbFKs",
      authDomain: "setap-4a.firebaseapp.com",
      projectId: "setap-4a",
      storageBucket: "setap-4a.firebasestorage.app",
      messagingSenderId: "342998131788",
      appId: "1:342998131788:web:e8035ec409b786253cc0e9",
      measurementId: "G-RYL5886JLE");
}
