// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
///
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC27Np2p70fgJpKonRhPP_u2P6ZoZG0swE',
    appId: '1:788597551090:web:f0370a55cfb9a55475c56b',
    messagingSenderId: '788597551090',
    projectId: 'setap4a-23a2e',
    authDomain: 'setap4a-23a2e.firebaseapp.com',
    storageBucket: 'setap4a-23a2e.firebasestorage.app',
    measurementId: 'G-D6W04QTNDN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiS6nlnd9t3u-rC5byO5ACWu-StzGOxqs',
    appId: '1:788597551090:android:0eb6565934341d5475c56b',
    messagingSenderId: '788597551090',
    projectId: 'setap4a-23a2e',
    storageBucket: 'setap4a-23a2e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZ6BrMxBlb96L4fwb41bZbFIRT5JUtRS0',
    appId: '1:788597551090:ios:1f8fdd3197eb7c1275c56b',
    messagingSenderId: '788597551090',
    projectId: 'setap4a-23a2e',
    storageBucket: 'setap4a-23a2e.firebasestorage.app',
    iosBundleId: 'com.example.setap4a',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZ6BrMxBlb96L4fwb41bZbFIRT5JUtRS0',
    appId: '1:788597551090:ios:1f8fdd3197eb7c1275c56b',
    messagingSenderId: '788597551090',
    projectId: 'setap4a-23a2e',
    storageBucket: 'setap4a-23a2e.firebasestorage.app',
    iosBundleId: 'com.example.setap4a',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC27Np2p70fgJpKonRhPP_u2P6ZoZG0swE',
    appId: '1:788597551090:web:7f951ebfb965cc2875c56b',
    messagingSenderId: '788597551090',
    projectId: 'setap4a-23a2e',
    authDomain: 'setap4a-23a2e.firebaseapp.com',
    storageBucket: 'setap4a-23a2e.firebasestorage.app',
    measurementId: 'G-N616NNPG1C',
  );
}
