name: Build and Test

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build:
    name: Android Emulator CI
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.1'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          cmdline-tools-version: 9477386
          accept-android-sdk-licenses: true
          log-accepted-android-sdk-licenses: false
          packages: >-
            platform-tools
            platforms;android-30
            build-tools;30.0.3
            emulator
            system-images;android-30;google_apis;x86

      - name: Create Android Emulator
        run: |
          echo "no" | avdmanager create avd -n test_emulator -k "system-images;android-30;google_apis;x86" -d pixel

      - name: Start X virtual framebuffer (Xvfb)
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb
          Xvfb :0 &
          export DISPLAY=:0

      - name: Start Android Emulator
        run: |
          export DISPLAY=:0
          nohup $(which emulator) -avd test_emulator -no-audio -no-window -gpu swiftshader_indirect -no-snapshot-save -no-accel &
          sleep 30

      - name: Wait for emulator to boot
        run: |
          export DISPLAY=:0
          export PATH=$PATH:$ANDROID_HOME/platform-tools/
          adb wait-for-device
          bootanim=""
          SECONDS=0
          timeout=300
          until [[ "$bootanim" == *stopped* || $SECONDS -gt $timeout ]]; do
            bootanim=$(adb shell getprop init.svc.bootanim 2>&1)
            echo "[$SECONDS sec] boot status: $bootanim"
            sleep 5
          done
          if [[ "$bootanim" != *stopped* ]]; then
            echo "❌ Emulator boot timed out after $timeout seconds."
            adb logcat -d || true
            exit 1
          fi
          echo "✅ Emulator booted in $SECONDS seconds."
          adb shell settings put global window_animation_scale 0
          adb shell settings put global transition_animation_scale 0
          adb shell settings put global animator_duration_scale 0

      - name: Check connected devices
        run: adb devices

      - name: Print Flutter doctor
        run: flutter doctor -v

      - name: Run unit tests
        run: flutter test

      - name: Run integration tests
        run: flutter test integration_test/
