name: Build and Test

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build:
    name: Android Emulator CI
    runs-on: ubuntu-latest
    timeout-minutes: 60
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.1'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          cmdline-tools-version: 9477386
          accept-android-sdk-licenses: true
          log-accepted-android-sdk-licenses: false
          packages: |
            platform-tools
            platforms;android-34
            build-tools;34.0.0
            emulator
            system-images;android-34;google_apis;x86_64

      - name: Create Android Emulator
        run: |
          echo "no" | avdmanager create avd -n test_emulator -k "system-images;android-34;google_apis;x86_64" -d pixel

      - name: Start X virtual framebuffer (Xvfb)
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb
          Xvfb :0 &
          export DISPLAY=:0

      - name: Start Android Emulator
        run: |
          export DISPLAY=:0
          nohup $(which emulator) -avd test_emulator -no-audio -no-window -gpu swiftshader_indirect &
          sleep 30



      - name: Wait for emulator to boot
        run: |
          export DISPLAY=:0
          export PATH=$PATH:$ANDROID_HOME/platform-tools/
          adb wait-for-device
          bootanim=""
          until [[ "$bootanim" == *stopped* ]]; do
            bootanim=$(adb shell getprop init.svc.bootanim 2>&1)
            echo "Waiting for emulator to boot..."
            sleep 5
          done
          adb shell settings put global window_animation_scale 0
          adb shell settings put global transition_animation_scale 0
          adb shell settings put global animator_duration_scale 0
        
      - name: Check connected devices
        run: adb devices

      - name: Print Flutter doctor
        run: flutter doctor -v

      - name: Run unit tests
        run: flutter test

      - name: Run integration tests
        run: flutter test integration_test/
