on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight UTC
  pull_request:
    branches: [main]
  push:
    branches: [main]

name: "Build and Test"
jobs:
  build:
     name: "Build and Test"
     runs-on: ubuntu-latest
     timeout-minutes: 60
     steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.0'
          channel: 'stable'

      - name: Install Dependencies
        run: flutter pub get

      - name: Download Android cmdline-tools  (needed to be installed before SDK license acceptance)
        run: |
          mkdir -p $HOME/android-sdk/cmdline-tools
          cd $HOME/android-sdk/cmdline-tools
          curl -o commandlinetools.zip https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip commandlinetools.zip
          mkdir latest
          mv cmdline-tools/* latest/
          
      - name: Accept Android SDK licenses
        env:
          ANDROID_SDK_ROOT: $HOME/android-sdk
          PATH: $HOME/android-sdk/cmdline-tools/latest/bin:$HOME/android-sdk/emulator:$HOME/android-sdk/platform-tools:$PATH
        run: |
          yes | sdkmanager --licenses
          
      - name: Install Android SDK components
        env:
          ANDROID_SDK_ROOT: $HOME/android-sdk
          PATH: $HOME/android-sdk/cmdline-tools/latest/bin:$HOME/android-sdk/emulator:$HOME/android-sdk/platform-tools:$PATH
        run: | 
          sdkmanager --install "platforms;android-34" "system-images;android-34;google_apis;x86_64" "emulator"

         
      - name: Create Android emulator (Pixel 7) - Added path avdmanager
        env:
          ANDROID_SDK_ROOT: $HOME/android-sdk
          PATH: $HOME/android-sdk/cmdline-tools/latest/bin:$HOME/android-sdk/emulator:$HOME/android-sdk/platform-tools:$PATH
        run: |
          echo "no" | avdmanager create avd -n pixel_7 -k "system-images;android-34;google_apis;x86_64" -d "pixel_7"

      - name: Launch emulator
        run: |
          nohup emulator -avd pixel_7 -no-audio -no-window -gpu swiftshader_indirect &
          adb wait-for-device
          adb shell settings put global window_animation_scale 0
          adb shell settings put global transition_animation_scale 0
          adb shell settings put global animator_duration_scale 0
        timeout-minutes: 60

      - name: Run unit tests
        run: flutter test

      - name: Run integration tests
        run: flutter test integration_test/