on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight UTC
  pull_request:
    branches: [main]
  push:
    branches: [main]

name: "Build and Test"
jobs:
  build:
    name: "Build and Test"
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.0'
          channel: 'stable'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-level: 34
          build-tools: '34.0.0'
          emulator: true
          ndk: false
          cmake: false

      - name: Accept Android SDK licenses
        run: yes | sdkmanager --licenses

      - name: Install dependencies
        run: flutter pub get
      
      - name: Install SDK components
        run: sdkmanager "platforms;android-34" "system-images;android-34;google_apis;x86_64" "emulator" "build-tools;34.0.0"

      - name: Create Android emulator (Pixel 7)
        run: |
          echo "no" | avdmanager create avd -n pixel_7 -k "system-images;android-34;google_apis;x86_64" -d "pixel_7"

      - name: Start emulator
        run: |
          nohup emulator -avd pixel_7 -no-audio -no-window -gpu swiftshader_indirect &

      - name: Wait for emulator to boot
        run: |
          adb wait-for-device
          adb shell settings put global window_animation_scale 0
          adb shell settings put global transition_animation_scale 0
          adb shell settings put global animator_duration_scale 0

      - name: Run unit tests
        run: flutter test

      - name: Run integration tests
        run: flutter test integration_test/